import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin"
import { extractRouterConfig } from "uploadthing/server"
import { ourFileRouter } from "./api/uploadthing/core"
import { AppProps } from "next/app"
import type { Metadata } from "next"
import "./globals.css"

import Nav from "./components/NavbarComponent"

import { Suspense } from "react"
import Loading from "./loading"
import UploadButtonPage from "./upload-button/page"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Component {...pageProps} />
		</>
	)
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className='font-play antialiased'>
				<NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
				<header>
					<Nav />
				</header>
				<Suspense fallback={<Loading />}>{children}</Suspense>
			</body>
		</html>
	)
}
