import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import { extractRouterConfig } from 'uploadthing/server'
import { ourFileRouter } from './api/uploadthing/core'
import { AppProps } from "next/app";
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

import Nav from './components/NavbarComponent'
import HeroComponent from './components/HeroComponent'
import Head from 'next/head'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
export function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<link
					href='https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700&display=swap'
					rel='stylesheet'
				/>
			</Head>
			<Component {...pageProps} />
		</>
	);
}


export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<NextSSRPlugin
					/**
					 * The `extractRouterConfig` will extract **only** the route configs
					 * from the router to prevent additional information from being
					 * leaked to the client. The data passed to the client is the same
					 * as if you were to fetch `/api/uploadthing` directly.
					 */
					routerConfig={extractRouterConfig(ourFileRouter)}
				/>
				<header>
					{/* <NavigationBar /> */}
					<Nav />
					{/* <Header /> */}
				</header>
                
				
				{children}
			</body>
		</html>
	);
}
